#!/bin/dash

# start compositor
compton -b &

# start tint2
(sleep 2s && tint2) &

# start last wallpaper
nitrogen --restore &

# add root access
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# start user accessibility bus - if not already running
/usr/lib/at-spi2-core/at-spi-bus-launcher --launch-immediately  &

#place network manager on the toolbar
nm-applet &

# provide a screensaver
xfce4-screensaver-command &
xfce4-screensaver &

#start pulseaudio before volumeicon so unmute works
start-pulseaudio-x11 &
volumeicon &

#place clipboard on the toolbar
clipit &

#put brightness controller and battery monitor on toolbar
xfce4-power-manager &

# set home screens correctly 
xrandr --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate normal --output eDP-1 --off &

