#!/bin/dash

# start compositor
compton -b &

# set natural scroll on touchpad (number value is exclusive, check yours with: 
# synclient command )
synclient VertScrollDelta=-109 &
synclient HorizScrollDelta=-109 &

#num lock keys starts on
numlockx on &

# start tint2
# (sleep 2s && tint2 -c ~/.config/tint2/ayu-systray.tint2rc) &
(sleep 2s && tint2 -c ~/.config/tint2/ayu-vertical-taskbar.tint2rc) &


# mx linux updates systray
ionice -c3 nice -n19 nohup python /usr/bin/apt-notifier.py 1>/dev/null 2>&1  &

# start last wallpaper
nitrogen --restore &

# export Qt variables
export QT_QPA_PLATFORMTHEME=gtk2
export QT_PLATFORMTHEME=gtk2
export QT_PLATFORM_PLUGIN=gtk2

# add root access
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# start user accessibility bus - if not already running
/usr/lib/at-spi2-core/at-spi-bus-launcher --launch-immediately  &

#place network manager on the toolbar
nm-applet &

# provide a screensaver
xfce4-screensaver-command &
xfce4-screensaver &

#start pulseaudio before volumeicon so unmute works
start-pulseaudio-x11 &
volumeicon &

#place clipboard on the toolbar
clipit &

#put brightness controller and battery monitor on toolbar
xfce4-power-manager &

# set home screens correctly 
xrandr --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate normal --output eDP-1 --off &

